# Generated by Django 5.1.1 on 2024-09-09 23:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('remitente', models.CharField(max_length=1000)),
                ('destinatario', models.CharField(max_length=1000)),
                ('fecha_hora_envio', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
